name: IBM Cloud Deploy

on:
  workflow_dispatch:
#  push:
#    branches: [ master,test ]
#  schedule:
#    - cron: '0 4 * * 0'

defaults:
  run:
    shell: bash

env:
  IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
  RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
  IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
  IBM_MEMORY: ${{ secrets.IBM_MEMORY }}
  V2_ID: ${{ secrets.V2_ID }}
  V2_PATH: ${{ secrets.V2_PATH }}
  ALTER_ID: ${{ secrets.ALTER_ID }}
  IBM_APP_NAME2: ${{ secrets.IBM_APP_NAME2 }}
  IBM_MEMORY2: ${{ secrets.IBM_MEMORY2 }}
  V2_ID2: ${{ secrets.V2_ID2 }}
  V2_PATH2: ${{ secrets.V2_PATH2 }}
  ALTER_ID2: ${{ secrets.ALTER_ID2 }}
  IBM_APP_NAME3: ${{ secrets.IBM_APP_NAME3 }}
  IBM_MEMORY3: ${{ secrets.IBM_MEMORY3 }}
  V2_ID3: ${{ secrets.V2_ID3 }}
  V2_PATH3: ${{ secrets.V2_PATH3 }}
  ALTER_ID3: ${{ secrets.ALTER_ID3 }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          ./deploy.sh
